version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgre-lead2
    restart: always
    environment:
      POSTGRES_USER: demetra
      POSTGRES_PASSWORD: demetra
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-main:
    image: redis:7
    container_name: redis-main
    restart: always
    environment:
      REDIS_PASSWORD: demetra
    ports:
      - "6379:6379"
    volumes:
      - redis_default_data:/data

  redis-cache:
    image: redis:7
    container_name: redis-cache
    restart: always
    environment:
      REDIS_PASSWORD: demetra
    ports:
      - "6380:6379"
    volumes:
      - redis_bull_data:/data

volumes:
  postgres_data:
  redis_default_data:
  redis_bull_data:
